### ISSUE TITLE
BytePropertyData change which breaks reading of values

### ISSUE THREAD

**Issue by bananaturtlesandwich** [atenfyr/UAssetAPI#19]
**Describe the bug**
A change has been made to how BytePropertyData works which makes it so reading the value will always return 0 (also the value type has been changed from integer to byte and as name maps can be normally larger than 256 and name map refs can be BytePropertyData this may be an issue)

**To Reproduce**
*for some reason I can't attach the program I compiled myself sorry*

Download this [example file](https://github.com/atenfyr/UAssetAPI/files/8720583/A01_TempleGardens.zip) (happens with any I think) and create a new test program like this (include newtonsoft.json as a nuget package):
```c#
using UAssetAPI;
using UAssetAPI.PropertyTypes;

Console.Write("Enter the filepath to the asset you want to print the value of the ByteProperties (the version is assumed 4.25 for this example): ");
UAsset TestAsset = new UAsset(@Console.ReadLine().Replace("\"", ""), UE4Version.VER_UE4_25);
foreach (var export in TestAsset.Exports)
    if (export is NormalExport norm)
        foreach (var property in norm.Data)
            if (property is BytePropertyData ByteProperty)
                Console.WriteLine(ByteProperty.Value);
Console.ReadKey();
```

now reference this [most recent dll](https://github.com/atenfyr/UAssetAPI/files/8720817/UAssetAPI.zip) and compile the program
You should get a result like this which only returns zeros:
![](https://user-images.githubusercontent.com/71292624/169154478-69d69db8-c165-415c-a788-7bfde17043a6.png)

now reference this [older version](https://github.com/atenfyr/UAssetAPI/files/8720813/UAssetAPI.zip) and compile the program
You should get a result like this which returns what I assume to be the actual values:
![](https://user-images.githubusercontent.com/71292624/169154630-d94314e2-399c-4efd-a5dd-e8bcdc3d29d6.png)

**Desktop:**
 - OS: Windows 10
 - Version or Commit: older .dll is [this commit](https://github.com/atenfyr/UAssetAPI/commit/fcaba23032f25af462a6bc625fdb8622a481ff5b) while newer .dll is [this one](https://github.com/atenfyr/UAssetAPI/commits/master)

**Comment by atenfyr** [comment]
In Unreal, ByteProperty can be serialized in one of two ways: either as a single byte, or as an enum value (represented by two FNames). UAssetAPI uses the "Value" field to represent the value of the property _if and only if the property is being serialized as a single byte_ (ByteType == BytePropertyType.Byte). It uses "EnumType" and "EnumValue" fields instead if the property is being serialized as an enum value (ByteType == BytePropertyType.FName). Different fields are used for these two cases in the current commit because they represent completely distinct types of data. In the example you provided, every single ByteProperty in the file is serialized as an enum value (ByteType == BytePropertyType.FName), so you should be examining the "EnumType" and "EnumValue" fields for the ByteProperties in this file instead to retrieve the data you're looking for.

**Comment by bananaturtlesandwich** [comment]
Okay thank you!
