### ISSUE TITLE
Game Crash after edit Uasset File

### ISSUE THREAD

**Issue by Marold57** [atenfyr/UAssetAPI#20]
Hello!

**Describe the bug**
After modify one Uasset the Game crash after the Title Screen when start the Campaign.
When i pack back the .pak file with no modifiyed Uassets the Game starts normal. Its a problem with the modifiyed Uassets.

**To Reproduce**
1. Set Uasset GUI to 4.26
2. Open Uasset and modify it and save it.
3. Copy the .uasset and .uexp in the extracted folder and pack back the Game .pak file
4. Game Crash when using the edited Uasset.

Game: Necromunda Hired Gun
Engine Version 4.26.1.0 ( Note: its a pre Version between 4.26 and 4.26.2 or something like (?) Im not sure :D)
[Necromunda Hired Gun 4.26.1.0.zip](https://github.com/atenfyr/UAssetAPI/files/8840331/Necromunda.Hired.Gun.4.26.1.0.zip)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Version or Commit: [863b6ef]

**Additional context**
Game crash with any other edited Uassets too.

Thanks and have a nice day!

**Comment by atenfyr** [comment]
Howdy,

Unfortunately, if UAssetGUI itself does not warn you about binary equality or experiences any other error or crash, I can't help you with this issue. I would do a couple of things to try and figure out the issue yourself:
- First, ensure that you are running on your own build of the latest commits or are using the latest released binary of UAssetGUI.
- Test to see if the crash occurs with fresh assets that are never opened by UAssetGUI. If it does, then the issue is likely with your packing setup.
- Test to see if the crash occurs with minimal changes, such as changing a single in-game cost or recipe integer value, and if you like, open the modified asset in a hex editor to ensure that only the one integer is changed. If the crash does occur, then for some reason the game or your setup is rejecting any modified assets.
- If the crash doesn't occur with those minimal changes, then there is likely something wrong with the modifications you made to the asset in this case.

atenfyr
