### ISSUE TITLE
UsmapBinaryReader created in Usmap never gets disposed

### ISSUE THREAD

**Issue by igromanru** [atenfyr/UAssetAPI#88]
**Describe the bug**
[Usmap(string path)](https://github.com/atenfyr/UAssetAPI/blob/48cd9604749905b5481f131bfc28ce35d455d0b5/UAssetAPI/Unversioned/Usmap.cs#L1169) creates a new UsmapBinaryReader with a Stream through [PathToReader(string p)](https://github.com/atenfyr/UAssetAPI/blob/48cd9604749905b5481f131bfc28ce35d455d0b5/UAssetAPI/Unversioned/Usmap.cs#L855C34-L855C56).
The created UsmapBinaryReader never gets disposed.
The [Read(UsmapBinaryReader compressedReader)](https://github.com/atenfyr/UAssetAPI/blob/48cd9604749905b5481f131bfc28ce35d455d0b5/UAssetAPI/Unversioned/Usmap.cs#L960C21-L960C61) function that uses the reader doesn't close it either.

**To Reproduce**
I've noticed it in [kismet-analyzer](https://github.com/trumank/kismet-analyzer/issues/4) as it was locking the usmap file.  
It was "fixed" there by creating a single Usmap and pass it through.
Still, the Stream that is used by UsmapBinaryReader never gets closed.

**Expected behavior**
If Usmap creates a new UsmapBinaryReader with a new Stream, it should call `UsmapBinaryReader::Dispose()` to close the Stream at the end. 

**Solution**
Implement IDisposable interface in Usmap.  
Usmap has two cstors, one accepts string, another a UsmapBinaryReader.  
I assume that if a developer creates a UsmapBinaryReader and passes it to a new Usmap that the developer should Dispose the reader himself.  
Therefore I would suggest to introduce a property for UsmapBinaryReader, which gets assigned with new UsmapBinaryReader only when `Usmap(string path)` is used and Dispose of it in the Dispose function, otherwise do nothing.   
Or always Dispose of the reader, no matter if it was passed as parameter or created in the Usmap.  
This uncertainty prevented me from making a PR, you have to decide what is the right approach here,

**Comment by atenfyr** [comment]
The current implementation shouldn't leave the file handle open, since the file is read in its entirety into a MemoryStream, then the file handle is closed (with a using block), and then the MemoryStream is operated upon directly for reading. (This is a little unconventional, but works OK given the size of the files generally being operated upon). I suppose the issue with kismet-analyzer is that multiple threads were attempting to read the .usmap file at once, which is a race condition. MemoryStream does not actually need to be explicitly disposed and will be cleaned up by the GC, just like byte arrays are (see: https://stackoverflow.com/questions/4274590/memorystream-close-or-memorystream-dispose). But, if you do want to explicitly dispose it for clarity, I would do so within the constructor, since the binary reader isn't ever accessed after Read() is called.
